name: Code push action

on:
  push:

jobs:
  code_push:
    runs-on: ubuntu-latest
    env:
      MAIN_BRANCH: main
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Verify commit message format
        if: steps.commit_message.outcome == 'success' # Only run if getting message succeeded
        run: |
          MESSAGE="${{ steps.commit_message.outputs.message }}"
          REGEX="^(fix|feat)\\(.+\\): .+$" # Updated regex
          if [[ "$MESSAGE" =~ $REGEX ]]; then
            echo "Commit message is valid: $MESSAGE"
          else
            echo "::error::Invalid commit message format: $MESSAGE"
            echo "::notice::Correct message formats: \"feat(CA-xxxx): implemented security layer\" or \"fix(CA-xxxx): updated max limit\""
            exit 1 # Fail the workflow
          fi          

      - name: Run ShellCheck
        uses: Azbagheri/shell-linter@latest
        with:
          path: "src/*.sh"
