name: Add version tag action

on:
  push:
    branches:
      - main

jobs:
  add_version_tag:
    runs-on: ubuntu-latest
    env:
      MAIN_BRANCH: main
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add tag version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: ${{ env.MAIN_BRANCH }}
          create_tag: true
          tag_prefix: 'v'
          
      - name: Version info
        run: | 
          echo "::notice:: Calculated version: ${{ steps.calculate-version.outputs.version-string }}" for branch  ${{ env.MAIN_BRANCH }}
