name: Code pull request target action

on:
  pull_request_target:
    branches:
      - main
    types: [closed]      

jobs:
  pull_request_target:
    runs-on: ubuntu-latest
    env:
      MAIN_BRANCH: main
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add tag version
        id: calculate-version
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: ${{ env.MAIN_BRANCH }}
          create_tag: true
          tag_prefix: 'v'
          
      - name: Use version
        run: | 
          echo "::notice:: Calculated version: ${{ steps.calculate-version.outputs.version-string }}" for branch  ${{ env.MAIN_BRANCH }}
