name: On Commit Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
          fetch-tags: true

      - name: Get changed files
        id: changed-files
        if: github.event_name == 'pull_request'
        run: |
          #if ${{ github.event_name == 'pull_request' }}; then
          #  echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          #else
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          #fi

      - name: Upload changed files
        if: github.event_name == 'pull_request'
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "$file was uploaded"
          done

      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        if: github.event_name == 'pull_request'
        with:
          main_branch: main
          create_tag: true
          tag_prefix: 'v'
          
      - name: Use version
        if: github.event_name == 'pull_request'
        run: | 
          echo "::notice:: Calculated version: ${{ steps.calculate-version.outputs.version-string }}"    
