name: On Commit Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Changed files (Push)
        if: github.event_name == 'push'
        run: |
          if [[ $(git rev-list --count HEAD) -gt 1 ]]; then
            echo "Changed files:"
            git diff-tree --no-commit-id --name-only HEAD^..HEAD
          else
            echo "Initial commit:"
            git show --name-only HEAD
          fi

      - name: Changed files (Pull Request)
        if: github.event_name == 'pull_request'
        run: |
          echo "Changed files (PR):"
          git diff-tree --no-commit-id --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
