name: Deploy Scripts

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'New Tag version'
        required: true
        type: string

      tag_version_current:
        description: 'Current Tag version'
        required: false
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'    

    steps:
      - name: Checkout code  
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          
      - name: Checking tags
        run: |
          if ! git show-ref --verify "refs/tags/${{ github.event.inputs.tag_version }}" > /dev/null 2>&1; then
            echo "Error: Tag ${{ github.event.inputs.tag_version }} does not exist"
            exit 1
          fi

          if ! [ -z "${{ github.event.inputs.tag_version_current }}" ]; then  # Check if input is not empty
            if ! git show-ref --verify "refs/tags/${{ github.event.inputs.tag_version_current }}" > /dev/null 2>&1; then
              echo "Error: Tag ${{ github.event.inputs.tag_version_current }} does not exist"
              exit 1
            fi
          fi      
  
