name: Deploy Scripts

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Scripts deployment'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Correct indentation for steps within 'steps'
        uses: actions/checkout@v3

      - name: Deploy scripts
        run: |
          echo '${{ github.event.inputs.app_version }}'
